# Generated by Django 5.2.13 on 2026-07-17 20:27

import apps.planner.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0010_supplierprofile_tenant'),
        ('campaigns', '0005_backfill_campaign_tenant'),
        ('inventory', '0009_mediaunit_is_publicly_listed_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPlannerShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('token_prefix', models.CharField(editable=False, max_length=16)),
                ('title', models.CharField(default='Live Media Planner', max_length=255)),
                ('allowed_cities', models.JSONField(blank=True, default=list)),
                ('allowed_regions', models.JSONField(blank=True, default=list)),
                ('allowed_inventory_types', models.JSONField(blank=True, default=list)),
                ('show_rates', models.BooleanField(default=False)),
                ('pricing_mode', models.CharField(choices=[('hidden', 'Hidden'), ('standard_selling_rate', 'Standard selling rate'), ('client_rate_card', 'Client rate card')], default='hidden', max_length=30)),
                ('allow_proposal_submission', models.BooleanField(default=True)),
                ('allow_image_download', models.BooleanField(default=False)),
                ('allow_map_data', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_planner_links', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_media_planner_links', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_planner_links', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.planner.models.proposal_reference, editable=False, max_length=20, unique=True)),
                ('campaign_name', models.CharField(max_length=255)),
                ('brand_company', models.CharField(blank=True, max_length=255)),
                ('objective', models.TextField(blank=True)),
                ('requested_start_date', models.DateField()),
                ('requested_end_date', models.DateField()),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('billing_gstin', models.CharField(blank=True, max_length=15)),
                ('billing_details', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(default='live_media_planner', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('availability_confirmed', 'Availability confirmed'), ('estimate_prepared', 'Estimate prepared'), ('sent_to_client', 'Sent to client'), ('client_approved', 'Client approved'), ('client_rejected', 'Client rejected'), ('converted_to_campaign', 'Converted to campaign'), ('expired', 'Expired')], default='submitted', max_length=30)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('preliminary_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('selected_unit_count', models.PositiveIntegerField(default=0)),
                ('availability_conflict_count', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, max_length=64)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_campaign_proposals', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_planner_proposals', to=settings.AUTH_USER_MODEL)),
                ('converted_campaign', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_proposal', to='campaigns.campaign')),
                ('estimate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_proposal', to='billing.campaignestimate')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_campaign_proposals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_proposals', to='tenants.tenant')),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='planner.mediaplannersharelink')),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignProposalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_public_id', models.UUIDField()),
                ('unit_code', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=255)),
                ('public_address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('facing_direction', models.CharField(blank=True, max_length=150)),
                ('display_format', models.CharField(blank=True, max_length=40)),
                ('is_illuminated', models.BooleanField(default=False)),
                ('monthly_rate_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_rate_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('availability_status', models.CharField(max_length=30)),
                ('availability_snapshot', models.JSONField(blank=True, default=dict)),
                ('media_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_lines', to='inventory.mediaunit')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='planner.campaignproposal')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('proposal', 'unit_public_id'), name='unique_unit_per_proposal')],
            },
        ),
        migrations.AddIndex(
            model_name='mediaplannersharelink',
            index=models.Index(fields=['tenant', 'revoked_at', 'expires_at'], name='planner_med_tenant__40e563_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignproposal',
            index=models.Index(fields=['tenant', 'status', 'submitted_at'], name='planner_cam_tenant__19c976_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignproposal',
            index=models.Index(fields=['share_link', 'idempotency_key'], name='planner_cam_share_l_2dfd78_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('share_link', 'idempotency_key'), name='unique_planner_submission_idempotency'),
        ),
    ]
