# Generated by Django 6.0.5 on 2026-07-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaplannersharelink',
            name='public_path',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
