# Generated by Django 5.2.13 on 2026-04-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_campaignaccesstoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignaccesstoken",
            name="token_value",
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
