# Generated by Django 5.2.13 on 2026-05-20 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaignaccesstoken_token_value'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='tenants.tenant'),
        ),
    ]
