# Generated by Django 5.2.13 on 2026-04-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_supplierprofile_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='invoices/'),
        ),
    ]
