# Generated by Django 5.2.13 on 2026-05-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_campaignestimate_campaignestimateline'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='booking_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='booking_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='cost_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='flex_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='installation_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='media_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='media_unit_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='other_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='site_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
