# Generated by Codex on 2026-05-04

from django.db import migrations, models


def migrate_campaign_estimate_statuses(apps, schema_editor):
    CampaignEstimate = apps.get_model("billing", "CampaignEstimate")

    for estimate in CampaignEstimate.objects.all():
        update_fields = []

        if estimate.status == "shared":
            estimate.status = "sent"
            update_fields.append("status")
        elif estimate.status == "finalized":
            estimate.status = "approved"
            update_fields.append("status")
            if getattr(estimate, "finalized_at", None) and not estimate.approved_at:
                estimate.approved_at = estimate.finalized_at
                update_fields.append("approved_at")
        elif estimate.status == "cancelled":
            estimate.status = "rejected"
            update_fields.append("status")
            if not estimate.rejected_at:
                estimate.rejected_at = estimate.shared_at or estimate.approved_at or estimate.created_at
                update_fields.append("rejected_at")

        if update_fields:
            estimate.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_invoiceline_booking_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignestimate",
            name="approval_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignestimate",
            name="approval_token_hash",
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="campaignestimate",
            name="approval_token_prefix",
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name="campaignestimate",
            name="approval_token_value",
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="campaignestimate",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_campaign_estimate_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="campaignestimate",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="campaignestimate",
            name="finalized_at",
        ),
    ]
