# Generated by Django 5.2.13 on 2026-05-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_campaignestimate_public_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignestimate',
            name='client_response_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
