# Generated by Django 5.2.13 on 2026-05-11 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_campaignestimate_client_response_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_invoice_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InvoiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('issued', 'Issued'), ('pdf_generated', 'PDF Generated'), ('pdf_downloaded', 'PDF Downloaded'), ('payment_recorded', 'Payment Recorded'), ('status_changed', 'Status Changed'), ('voided', 'Voided')], max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_events', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='billing.invoice')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['invoice', 'event_type'], name='billing_inv_invoice_d8d3c0_idx'), models.Index(fields=['created_at'], name='billing_inv_created_5b9534_idx')],
            },
        ),
    ]
