# Generated by Django 5.2.13 on 2026-05-12 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_payment_recorded_by_invoiceevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('issued', 'Issued'), ('pdf_generated', 'PDF Generated'), ('pdf_downloaded', 'PDF Downloaded'), ('payment_recorded', 'Payment Recorded'), ('credit_note_created', 'Credit Note Created'), ('status_changed', 'Status Changed'), ('voided', 'Voided')], max_length=30),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('card', 'Card'), ('cheque', 'Cheque'), ('adjustment', 'Ledger Adjustment')], max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoice_credit_notes', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='billing.invoice')),
            ],
            options={
                'ordering': ['-credit_date', '-created_at'],
            },
        ),
    ]
