# Generated by Django 5.2.13 on 2026-05-20 21:16

import django.db.models.deletion
from django.db import migrations, models


def backfill_supplier_profile_tenant(apps, schema_editor):
    SupplierProfile = apps.get_model("billing", "SupplierProfile")
    Tenant = apps.get_model("tenants", "Tenant")
    default_tenant = Tenant.objects.filter(is_default=True, tenant_type="client").first()
    if default_tenant:
        SupplierProfile.objects.filter(tenant__isnull=True).update(tenant=default_tenant)


def clear_supplier_profile_tenant(apps, schema_editor):
    apps.get_model("billing", "SupplierProfile").objects.update(tenant=None)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_invoiceevent_event_type_creditnote'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_profiles', to='tenants.tenant'),
        ),
        migrations.RunPython(backfill_supplier_profile_tenant, clear_supplier_profile_tenant),
    ]
