ADMIN = "admin"
SALES = "sales"
OPERATIONS = "operations"
FIELD_STAFF = "field_staff"
FINANCE = "finance"
CLIENT = "client"

BACKOFFICE_ROLES = (ADMIN, SALES, OPERATIONS, FINANCE)
ALL_ROLES = (ADMIN, SALES, OPERATIONS, FIELD_STAFF, FINANCE, CLIENT)
FIELD_ASSIGNABLE_ROLES = (FIELD_STAFF, OPERATIONS)
