ADMIN = "admin"
SALES = "sales"
OPERATIONS = "operations"
FINANCE = "finance"
CLIENT = "client"

BACKOFFICE_ROLES = (ADMIN, SALES, OPERATIONS, FINANCE)
ALL_ROLES = (ADMIN, SALES, OPERATIONS, FINANCE, CLIENT)
