ADMIN = "admin"
SALES = "sales"
OPERATIONS = "operations"
FIELD_STAFF = "field_staff"
POE_REVIEWER = "poe_reviewer"
FINANCE = "finance"
INVENTORY_MANAGER = "inventory_manager"
CLIENT = "client"

BACKOFFICE_ROLES = (ADMIN, SALES, OPERATIONS, FINANCE)
ALL_ROLES = (ADMIN, SALES, OPERATIONS, FIELD_STAFF, FINANCE, CLIENT)
FIELD_ASSIGNABLE_ROLES = (FIELD_STAFF, OPERATIONS)

TEAM_ASSIGNABLE_ROLES = (ADMIN, OPERATIONS, FIELD_STAFF, POE_REVIEWER, FINANCE, INVENTORY_MANAGER, CLIENT)
