# Generated by Django 5.2.13 on 2026-05-12 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(max_length=12)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_slow', models.BooleanField(db_index=True, default=False)),
                ('category', models.CharField(choices=[('auth', 'Auth'), ('billing', 'Billing'), ('campaigns', 'Campaigns'), ('inventory', 'Inventory'), ('bookings', 'Bookings'), ('poe', 'POE'), ('issues', 'Issues'), ('notifications', 'Notifications'), ('setup', 'Setup'), ('mobile', 'Mobile'), ('observability', 'Observability'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('query_count', models.PositiveIntegerField(blank=True, null=True)),
                ('query_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_slow', '-created_at'], name='observabili_is_slow_a13802_idx'), models.Index(fields=['category', '-created_at'], name='observabili_categor_4ef427_idx'), models.Index(fields=['user', '-created_at'], name='observabili_user_id_2fd372_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('entity_type', models.CharField(db_index=True, max_length=80)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('client_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('invoice_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='observabili_event_t_d82389_idx'), models.Index(fields=['entity_type', 'entity_id'], name='observabili_entity__856944_idx'), models.Index(fields=['severity', '-created_at'], name='observabili_severit_70b5cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(choices=[('import', 'Import'), ('export', 'Export')], max_length=20)),
                ('resource_type', models.CharField(choices=[('inventory_sites', 'Inventory Sites'), ('media_units', 'Media Units'), ('clients', 'Clients'), ('campaigns', 'Campaigns'), ('invoices', 'Invoices'), ('client_statements', 'Client Statements'), ('poe_reports', 'POE Reports')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('original_file', models.FileField(blank=True, max_length=500, null=True, upload_to='imports/')),
                ('output_file', models.FileField(blank=True, max_length=500, null=True, upload_to='exports/')),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_success', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('preview_rows', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_type', 'resource_type', '-created_at'], name='observabili_job_typ_09c542_idx'), models.Index(fields=['status', '-created_at'], name='observabili_status_6463e0_idx')],
            },
        ),
    ]
