# Generated by Django 5.2.13 on 2026-05-12 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('metric', models.CharField(choices=[('slow_requests', 'Slow Requests'), ('failed_notifications', 'Failed Notifications'), ('suspicious_poes', 'Suspicious POEs'), ('overdue_poe_reviews', 'Overdue POE Reviews'), ('breached_issues', 'Breached Issues'), ('overdue_invoices', 'Overdue Invoices')], max_length=40, unique=True)),
                ('threshold', models.PositiveIntegerField(default=1)),
                ('window_minutes', models.PositiveIntegerField(default=60)),
                ('cooldown_minutes', models.PositiveIntegerField(default=60)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['metric'],
            },
        ),
        migrations.AddField(
            model_name='importexportjob',
            name='filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='importexportjob',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('previewed', 'Previewed'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('pending', 'Pending'), ('validated', 'Validated'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(db_index=True, max_length=40)),
                ('observed_value', models.PositiveIntegerField(default=0)),
                ('threshold', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(db_index=True, max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='observability.alertrule')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['metric', '-created_at'], name='observabili_metric_76ff21_idx'), models.Index(fields=['severity', '-created_at'], name='observabili_severit_b5c129_idx')],
            },
        ),
    ]
