# Generated by Django 5.2.13 on 2026-05-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0002_alertrule_importexportjob_filters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importexportjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importexportjob',
            name='rows_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importexportjob',
            name='rows_updated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importexportjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
