# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observability", "0003_importexportjob_completed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrule",
            name="metric",
            field=models.CharField(
                choices=[
                    ("slow_requests", "Slow Requests"),
                    ("failed_api_requests", "Failed API Requests"),
                    ("failed_notifications", "Failed Notifications"),
                    ("failed_import_export_jobs", "Failed Import/Export Jobs"),
                    ("suspicious_poes", "Suspicious POEs"),
                    ("overdue_poe_reviews", "Overdue POE Reviews"),
                    ("breached_issues", "Breached Issues"),
                    ("overdue_invoices", "Overdue Invoices"),
                ],
                max_length=40,
                unique=True,
            ),
        ),
    ]
