# Generated by Django 5.2.13 on 2026-05-18 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0005_alertevent_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importexportjob',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importexportjob',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importexportjob',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_attempts', to='observability.importexportjob'),
        ),
    ]
