# Generated by Django 5.2.13 on 2026-05-19 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0008_alter_alertrule_metric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedOperationalView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('name', models.CharField(max_length=120)),
                ('view_type', models.CharField(choices=[('operations', 'Operations'), ('search', 'Search'), ('alerts', 'Alerts'), ('campaigns', 'Campaigns'), ('billing', 'Billing'), ('poe', 'POE'), ('import_export', 'Import / Export')], db_index=True, default='operations', max_length=30)),
                ('module', models.CharField(blank=True, db_index=True, max_length=40)),
                ('search_query', models.CharField(blank=True, max_length=120)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_operational_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['view_type', 'name'],
                'indexes': [models.Index(fields=['user', 'view_type', 'updated_at'], name='observabili_user_id_e88390_idx'), models.Index(fields=['company_name', 'module'], name='observabili_company_ceedc9_idx')],
                'unique_together': {('user', 'company_name', 'name')},
            },
        ),
    ]
