# Generated by Django 5.2.13 on 2026-05-19 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0009_savedoperationalview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidgetPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('widget_key', models.CharField(max_length=80)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widget_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'widget_key'],
                'indexes': [models.Index(fields=['user', 'company_name', 'sort_order'], name='observabili_user_id_9d306c_idx')],
                'unique_together': {('user', 'company_name', 'widget_key')},
            },
        ),
    ]
