# Generated by Django 5.2.13 on 2026-05-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0010_dashboardwidgetpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='metric',
            field=models.CharField(choices=[('slow_requests', 'Slow Requests'), ('failed_api_requests', 'Failed API Requests'), ('failed_notifications', 'Failed Notifications'), ('failed_import_export_jobs', 'Failed Import/Export Jobs'), ('suspicious_poes', 'Suspicious POEs'), ('overdue_poe_reviews', 'Overdue POE Reviews'), ('poe_sla_breaches', 'POE SLA Breaches'), ('campaigns_at_risk', 'Campaigns At Risk'), ('system_health_degraded', 'System Health Degraded'), ('breached_issues', 'Breached Issues'), ('overdue_invoices', 'Overdue Invoices')], max_length=40, unique=True),
        ),
    ]
