# Generated by Django 5.2.13 on 2026-05-20 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0011_alter_alertrule_metric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('mode', models.CharField(choices=[('normal', 'Normal'), ('maintenance', 'Maintenance'), ('degraded', 'Degraded'), ('read_only', 'Read Only')], db_index=True, default='normal', max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_mode_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'operational mode',
                'verbose_name_plural': 'operational mode',
            },
        ),
    ]
