# Generated by Django 5.2.13 on 2026-05-20 21:14

import django.db.models.deletion
from django.db import migrations, models


def backfill_observability_tenants(apps, schema_editor):
    ImportExportJob = apps.get_model("observability", "ImportExportJob")
    SavedOperationalView = apps.get_model("observability", "SavedOperationalView")
    DashboardWidgetPreference = apps.get_model("observability", "DashboardWidgetPreference")
    AlertEvent = apps.get_model("observability", "AlertEvent")
    Tenant = apps.get_model("tenants", "Tenant")

    default_tenant = Tenant.objects.filter(is_default=True, tenant_type="client").first()
    for job in ImportExportJob.objects.select_related("created_by").filter(tenant__isnull=True).iterator():
        tenant = getattr(job.created_by, "tenant", None) or default_tenant
        if tenant:
            ImportExportJob.objects.filter(pk=job.pk, tenant__isnull=True).update(tenant=tenant)

    for view in SavedOperationalView.objects.select_related("user").filter(tenant__isnull=True).iterator():
        tenant = getattr(view.user, "tenant", None)
        if tenant:
            SavedOperationalView.objects.filter(pk=view.pk, tenant__isnull=True).update(tenant=tenant)

    for preference in DashboardWidgetPreference.objects.select_related("user").filter(tenant__isnull=True).iterator():
        tenant = getattr(preference.user, "tenant", None)
        if tenant:
            DashboardWidgetPreference.objects.filter(pk=preference.pk, tenant__isnull=True).update(tenant=tenant)

    for event in AlertEvent.objects.select_related("rule").filter(tenant__isnull=True, rule__tenant__isnull=False).iterator():
        AlertEvent.objects.filter(pk=event.pk, tenant__isnull=True).update(tenant=event.rule.tenant)


def clear_observability_tenants(apps, schema_editor):
    for model_name in ["ImportExportJob", "SavedOperationalView", "DashboardWidgetPreference", "AlertEvent", "AlertRule"]:
        apps.get_model("observability", model_name).objects.update(tenant=None)


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0012_operationalmode'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dashboardwidgetpreference',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widget_preferences', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='importexportjob',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_export_jobs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='savedoperationalview',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_operational_views', to='tenants.tenant'),
        ),
        migrations.RunPython(backfill_observability_tenants, clear_observability_tenants),
    ]
