# Generated by Django 5.2.13 on 2026-04-20 19:55

import apps.poe.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proofofexecutionmedia',
            options={'ordering': ['-captured_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='proofofexecutionmedia',
            name='captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_poe_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proofofexecutionmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.poe.models.poe_media_upload_to),
        ),
        migrations.AddField(
            model_name='proofofexecutionmedia',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proofofexecutionmedia',
            name='captured_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proofofexecutionmedia',
            name='media_url',
            field=models.URLField(blank=True),
        ),
    ]
