# Generated by Django 5.2.13 on 2026-05-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe', '0003_proofofexecution_captured_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofexecution',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proofofexecution',
            name='review_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proofofexecution',
            name='review_sla_status',
            field=models.CharField(choices=[('on_track', 'On Track'), ('overdue', 'Overdue'), ('reviewed', 'Reviewed')], default='on_track', max_length=20),
        ),
        migrations.AddField(
            model_name='proofofexecution',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
