# Generated by Django 5.2.13 on 2026-05-12 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_agreed_media_cost_booking_cost_notes_and_more'),
        ('poe', '0004_proofofexecution_review_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofexecution',
            name='client_upload_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddConstraint(
            model_name='proofofexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('client_upload_id', ''), _negated=True), fields=('client_upload_id',), name='unique_non_empty_poe_client_upload_id'),
        ),
    ]
