# Generated by Django 6.0.5 on 2026-07-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe', '0005_proofofexecution_client_upload_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofexecutionmedia',
            name='bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proofofexecutionmedia',
            name='format',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='proofofexecutionmedia',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proofofexecutionmedia',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proofofexecutionmedia',
            name='provider',
            field=models.CharField(choices=[('r2', 'Cloudflare R2'), ('cloudinary', 'Cloudinary')], db_index=True, default='r2', max_length=30),
        ),
        migrations.AddField(
            model_name='proofofexecutionmedia',
            name='provider_asset_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proofofexecutionmedia',
            name='provider_public_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='proofofexecutionmedia',
            name='provider_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proofofexecutionmedia',
            name='resource_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='proofofexecutionmedia',
            name='secure_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='proofofexecutionmedia',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proofofexecutionmedia',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
