# Generated by Django 5.2.13 on 2026-05-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('operations', 'Operations'), ('field_staff', 'Field Staff'), ('finance', 'Finance'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
