# Generated by Django 5.2.13 on 2026-07-17 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_seed_default_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='setup_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Company Admin'), ('sales', 'Sales'), ('operations', 'Operations Manager'), ('field_staff', 'Field Staff'), ('poe_reviewer', 'POE Reviewer'), ('finance', 'Finance'), ('inventory_manager', 'Inventory Manager'), ('client', 'Client Viewer')], default='client', max_length=20),
        ),
    ]
