# Generated by Django 6.0.5 on 2026-07-18 20:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_region_user_reports_to_user_setup_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRefreshSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_refresh_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_activity_at', '-created_at'),
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='users_authr_user_id_8491b4_idx'), models.Index(fields=['last_activity_at'], name='users_authr_last_ac_69f479_idx')],
            },
        ),
    ]
