# Generated by Django 5.2.13 on 2026-04-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_mediasiteimage_mediaunitimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaunit',
            name='facing_direction',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
