# Generated by Django 5.2.13 on 2026-05-11 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_update_mediaunit_site_type_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediasite',
            name='location_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('first_verified_poe', 'First verified POE'), ('admin_verified', 'Admin verified')], max_length=30),
        ),
        migrations.AddField(
            model_name='mediasite',
            name='location_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('provisional', 'Provisional'), ('verified', 'Verified'), ('suspicious', 'Suspicious')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='mediasite',
            name='location_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediasite',
            name='location_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_site_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
