# Generated by Django 5.2.13 on 2026-07-17 20:27

import uuid
from django.db import migrations, models


def populate_public_ids(apps, schema_editor):
    MediaUnit = apps.get_model("inventory", "MediaUnit")
    for unit in MediaUnit.objects.filter(public_id__isnull=True).iterator(chunk_size=500):
        unit.public_id = uuid.uuid4()
        unit.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_backfill_mediasite_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaunit',
            name='is_publicly_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediaunit',
            name='public_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mediaunit',
            name='public_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaunit',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(populate_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='mediaunit',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
