# Generated by Django 6.0.5 on 2026-07-20 11:51

import apps.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_mediaunit_is_publicly_listed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediasiteimage',
            name='bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediasiteimage',
            name='format',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='mediasiteimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediasiteimage',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediasiteimage',
            name='provider',
            field=models.CharField(choices=[('r2', 'Cloudflare R2'), ('cloudinary', 'Cloudinary')], db_index=True, default='r2', max_length=30),
        ),
        migrations.AddField(
            model_name='mediasiteimage',
            name='provider_asset_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediasiteimage',
            name='provider_public_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mediasiteimage',
            name='provider_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mediasiteimage',
            name='resource_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='mediasiteimage',
            name='secure_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='mediasiteimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediasiteimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaunitimage',
            name='bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaunitimage',
            name='format',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='mediaunitimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaunitimage',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediaunitimage',
            name='provider',
            field=models.CharField(choices=[('r2', 'Cloudflare R2'), ('cloudinary', 'Cloudinary')], db_index=True, default='r2', max_length=30),
        ),
        migrations.AddField(
            model_name='mediaunitimage',
            name='provider_asset_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediaunitimage',
            name='provider_public_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mediaunitimage',
            name='provider_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mediaunitimage',
            name='resource_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='mediaunitimage',
            name='secure_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='mediaunitimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediaunitimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediasiteimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.inventory.models.site_image_upload_to),
        ),
        migrations.AlterField(
            model_name='mediaunitimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.inventory.models.unit_image_upload_to),
        ),
    ]
