# Generated by Django 5.2.13 on 2026-05-02 14:03

import apps.issues.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_assignment_status'),
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReportToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=apps.issues.models.issue_report_token_default, max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='first_response_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='sla_status',
            field=models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('breached', 'Breached')], default='on_track', max_length=20),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['sla_status', 'resolution_due_at'], name='issues_issu_sla_sta_a85c97_idx'),
        ),
        migrations.AddField(
            model_name='issuereporttoken',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_report_tokens', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='issuereporttoken',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issue_report_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='issuereporttoken',
            index=models.Index(fields=['token', 'expires_at'], name='issues_issu_token_38ccad_idx'),
        ),
    ]
