# Generated by Django 5.2.13 on 2026-05-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationlog',
            name='notification_type',
            field=models.CharField(choices=[('campaign_booked', 'Campaign Booked'), ('poe_uploaded', 'POE Uploaded'), ('invoice_issued', 'Invoice Issued'), ('payment_recorded', 'Payment Recorded'), ('suspicious_poe', 'Suspicious POE'), ('issue_reported', 'Issue Reported')], max_length=30),
        ),
    ]
