# Generated by Django 5.2.13 on 2026-05-12 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_escalated_at_issue_escalated_by_and_more'),
        ('notifications', '0002_alter_emailnotificationlog_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotificationlog',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notification_logs', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='emailnotificationlog',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailnotificationlog',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailnotificationlog',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailnotificationlog',
            name='notification_type',
            field=models.CharField(choices=[('campaign_booked', 'Campaign Booked'), ('poe_uploaded', 'POE Uploaded'), ('invoice_issued', 'Invoice Issued'), ('payment_recorded', 'Payment Recorded'), ('suspicious_poe', 'Suspicious POE'), ('issue_reported', 'Issue Reported'), ('issue_escalated', 'Issue Escalated')], max_length=30),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('campaign_booked', 'Campaign Booked'), ('poe_uploaded', 'POE Uploaded'), ('invoice_issued', 'Invoice Issued'), ('payment_recorded', 'Payment Recorded'), ('suspicious_poe', 'Suspicious POE'), ('issue_reported', 'Issue Reported'), ('issue_escalated', 'Issue Escalated')], max_length=30)),
                ('email_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'notification_type'],
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
