# Generated by Django 5.2.13 on 2026-05-12 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_emailnotificationlog_issue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_role', models.CharField(blank=True, db_index=True, max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(choices=[('campaign_booked', 'Campaign Booked'), ('poe_uploaded', 'POE Uploaded'), ('invoice_issued', 'Invoice Issued'), ('payment_recorded', 'Payment Recorded'), ('suspicious_poe', 'Suspicious POE'), ('issue_reported', 'Issue Reported'), ('issue_escalated', 'Issue Escalated')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('internal', 'Internal'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='internal', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['recipient_role', 'is_read', '-created_at'], name='notificatio_recipie_2a9148_idx'), models.Index(fields=['event_type', '-created_at'], name='notificatio_event_t_bb6b48_idx')],
            },
        ),
    ]
