# Generated by Django 5.2.13 on 2026-05-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='in_app_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailnotificationlog',
            name='notification_type',
            field=models.CharField(choices=[('campaign_booked', 'Campaign Booked'), ('poe_uploaded', 'POE Uploaded'), ('invoice_issued', 'Invoice Issued'), ('payment_recorded', 'Payment Recorded'), ('suspicious_poe', 'Suspicious POE'), ('issue_reported', 'Issue Reported'), ('issue_escalated', 'Issue Escalated'), ('alert_triggered', 'Alert Triggered')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('campaign_booked', 'Campaign Booked'), ('poe_uploaded', 'POE Uploaded'), ('invoice_issued', 'Invoice Issued'), ('payment_recorded', 'Payment Recorded'), ('suspicious_poe', 'Suspicious POE'), ('issue_reported', 'Issue Reported'), ('issue_escalated', 'Issue Escalated'), ('alert_triggered', 'Alert Triggered')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('campaign_booked', 'Campaign Booked'), ('poe_uploaded', 'POE Uploaded'), ('invoice_issued', 'Invoice Issued'), ('payment_recorded', 'Payment Recorded'), ('suspicious_poe', 'Suspicious POE'), ('issue_reported', 'Issue Reported'), ('issue_escalated', 'Issue Escalated'), ('alert_triggered', 'Alert Triggered')], max_length=30),
        ),
    ]
