# Generated by Django 5.2.13 on 2026-05-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notificationpreference_in_app_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationlog',
            name='notification_type',
            field=models.CharField(choices=[('campaign_booked', 'Campaign Booked'), ('poe_uploaded', 'POE Uploaded'), ('invoice_issued', 'Invoice Issued'), ('payment_recorded', 'Payment Recorded'), ('suspicious_poe', 'Suspicious POE'), ('issue_reported', 'Issue Reported'), ('issue_escalated', 'Issue Escalated'), ('alert_triggered', 'Alert Triggered'), ('inventory_import_completed', 'Inventory Import Completed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('campaign_booked', 'Campaign Booked'), ('poe_uploaded', 'POE Uploaded'), ('invoice_issued', 'Invoice Issued'), ('payment_recorded', 'Payment Recorded'), ('suspicious_poe', 'Suspicious POE'), ('issue_reported', 'Issue Reported'), ('issue_escalated', 'Issue Escalated'), ('alert_triggered', 'Alert Triggered'), ('inventory_import_completed', 'Inventory Import Completed')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('campaign_booked', 'Campaign Booked'), ('poe_uploaded', 'POE Uploaded'), ('invoice_issued', 'Invoice Issued'), ('payment_recorded', 'Payment Recorded'), ('suspicious_poe', 'Suspicious POE'), ('issue_reported', 'Issue Reported'), ('issue_escalated', 'Issue Escalated'), ('alert_triggered', 'Alert Triggered'), ('inventory_import_completed', 'Inventory Import Completed')], max_length=30),
        ),
    ]
