# Generated by Codex on 2026-05-15

from django.db import migrations, models


NOTIFICATION_TYPE_CHOICES = [
    ("campaign_booked", "Campaign Booked"),
    ("poe_uploaded", "POE Uploaded"),
    ("invoice_issued", "Invoice Issued"),
    ("payment_recorded", "Payment Recorded"),
    ("suspicious_poe", "Suspicious POE"),
    ("issue_reported", "Issue Reported"),
    ("issue_escalated", "Issue Escalated"),
    ("alert_triggered", "Alert Triggered"),
    ("inventory_import_completed", "Inventory Import Completed"),
    ("inventory_import_failed", "Inventory Import Failed"),
    ("export_completed", "Export Completed"),
    ("export_failed", "Export Failed"),
    ("poe_approved", "POE Approved"),
    ("poe_rejected", "POE Rejected"),
    ("system_diagnostic_alert", "System Diagnostic Alert"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_alter_emailnotificationlog_notification_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailnotificationlog",
            name="notification_type",
            field=models.CharField(choices=NOTIFICATION_TYPE_CHOICES, max_length=30),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(choices=NOTIFICATION_TYPE_CHOICES, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notification_type",
            field=models.CharField(choices=NOTIFICATION_TYPE_CHOICES, max_length=30),
        ),
    ]
