# Generated by Django 5.2.13 on 2026-05-20 21:14

import django.db.models.deletion
from django.db import migrations, models


def backfill_notification_tenants(apps, schema_editor):
    EmailNotificationLog = apps.get_model("notifications", "EmailNotificationLog")
    Notification = apps.get_model("notifications", "Notification")
    Tenant = apps.get_model("tenants", "Tenant")

    default_tenant = Tenant.objects.filter(is_default=True, tenant_type="client").first()
    for log in EmailNotificationLog.objects.select_related("campaign", "booking__campaign", "poe_record__booking__campaign", "issue__booking__campaign").filter(tenant__isnull=True).iterator():
        tenant = None
        if log.campaign_id:
            tenant = getattr(log.campaign, "tenant", None)
        elif log.booking_id:
            tenant = getattr(log.booking.campaign, "tenant", None)
        elif log.poe_record_id:
            tenant = getattr(log.poe_record.booking.campaign, "tenant", None)
        elif log.issue_id:
            tenant = getattr(log.issue.booking.campaign, "tenant", None)
        tenant = tenant or default_tenant
        if tenant:
            EmailNotificationLog.objects.filter(pk=log.pk, tenant__isnull=True).update(tenant=tenant)

    for notification in Notification.objects.select_related("recipient").filter(tenant__isnull=True).iterator():
        tenant = getattr(notification.recipient, "tenant", None) or default_tenant
        if tenant:
            Notification.objects.filter(pk=notification.pk, tenant__isnull=True).update(tenant=tenant)


def clear_notification_tenants(apps, schema_editor):
    apps.get_model("notifications", "EmailNotificationLog").objects.update(tenant=None)
    apps.get_model("notifications", "Notification").objects.update(tenant=None)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_expand_notification_preference_types'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotificationlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notification_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.tenant'),
        ),
        migrations.RunPython(backfill_notification_tenants, clear_notification_tenants),
    ]
